### ISSUE TITLE
🐞Do not execute the function that is called within 'Workmanager.executeTask'

### ISSUE THREAD

**Issue by ZotInfo** [vrtdev/flutter_workmanager#154]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |               |
| Xcode version        |               |
| Swift version        |               |
| iOS deployment target|               |

**Describe the error**
After closing the application the service does not continue running in the background and records these messages in the Android Studio logcat

```
E/ActivityThread(10619): Activity br.com.infogen.gpstracker.MainActivity has leaked ServiceConnection com.almoullim.background_location.BackgroundLocationPlugin$mServiceConnection$1@1f88f6 that was originally bound here
E/ActivityThread(10619): android.app.ServiceConnectionLeaked: Activity br.com.infogen.gpstracker.MainActivity has leaked ServiceConnection com.almoullim.background_location.BackgroundLocationPlugin$mServiceConnection$1@1f88f6 that was originally bound here
E/ActivityThread(10619): 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1619)
E/ActivityThread(10619): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1511)
E/ActivityThread(10619): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1674)
E/ActivityThread(10619): 	at android.app.ContextImpl.bindService(ContextImpl.java:1627)
E/ActivityThread(10619): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
E/ActivityThread(10619): 	at com.almoullim.background_location.BackgroundLocationPlugin.onMethodCall(BackgroundLocationPlugin.kt:83)
E/ActivityThread(10619): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/ActivityThread(10619): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/ActivityThread(10619): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/ActivityThread(10619): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/ActivityThread(10619): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/ActivityThread(10619): 	at android.os.Looper.loop(Looper.java:160)
E/ActivityThread(10619): 	at android.app.ActivityThread.main(ActivityThread.java:6923)
E/ActivityThread(10619): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread(10619): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/ActivityThread(10619): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
W/FlutterJNI(10619): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: almoullim.com/background_location. Response ID: 0
I/chatty  (10619): uid=10477(br.com.infogen.gpstracker) identical 1 line
W/FlutterJNI(10619): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: almoullim.com/background_location. Response ID: 0
```

**Output of `flutter doctor -v`**
```
C:\KB\Android\GPSTracker\gpstracker>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [versÃ£o 10.0.17763.914], locale pt-BR)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\infogen-desenv-7000\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • moto g 6 play • 0046718621 • android-arm • Android 9 (API 28)

• No issues found!
```

**Comment by petermnt** [comment]
This is not the use case of this plugin. This is specifically to trigger background tasks that do a certain workload and finish, not to keep services running in the background.
