### ISSUE TITLE
The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.

### ISSUE THREAD

**Issue by sieryuu** [vrtdev/flutter_workmanager#156]
Is there any workaround for Geolocator inside WorkManager task?

What have I missed?

```
void updateDeviceLocationIsolate() async {
  workManager.Workmanager.executeTask((task, inputData) async {
    print("background working is running");

    Geolocator geolocator = new Geolocator();
    // Geolocator geolocator = Geolocator()..forceAndroidLocationManager = true;
    Position location;
    try {
      location = await geolocator.getCurrentPosition(
          desiredAccuracy: LocationAccuracy.high);
      if (location != null && location.latitude != null) {
        print(
            "lat ${location.latitude}, lng ${location.longitude}, time ${location.timestamp.toIso8601String()}");
      } else {
        print("locatin is null");
      }
    } catch (e) {
      print("error: $e");
    }
    return Future.value(true);
  });
}
```

```
 @override
  void initState() {

    WidgetsFlutterBinding.ensureInitialized();
    workManager.Workmanager.initialize(updateDeviceLocationIsolate,
        isInDebugMode: true);
    workManager.Workmanager.registerPeriodicTask("1", "update-location");

    super.initState();
  }
```

Above code will expect error
```
D/EGL_emulation( 8019): eglCreateContext: 0xc2e603c0: maj 2 min 0 rcv 2
D/HostConnection( 8019): HostConnection::get() New Host Connection established 0xd6cc7000, tid 8143
D/HostConnection( 8019): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2
D/EGL_emulation( 8019): eglMakeCurrent: 0xc2e603c0: ver 2 0 (tinfo 0xed5890e0)
I/flutter ( 8019): background working is running
E/GooglePlayServicesUtil( 8019): The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
E/MethodChannel#flutter.baseflow.com/google_api_availability/methods( 8019): Failed to handle method call
E/MethodChannel#flutter.baseflow.com/google_api_availability/methods( 8019): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
E/MethodChannel#flutter.baseflow.com/google_api_availability/methods( 8019): 	at com.google.android.gms.common.GooglePlayServicesUtilLight.isGooglePlayServicesAvailable(Unknown Source:12)
E/MethodChannel#flutter.baseflow.com/google_api_availability/methods( 8019): 	at com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(Unknown Source:5)
E/MethodChannel#flutter.baseflow.com/google_api_availability/methods( 8019): 	at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source:94)
E/MethodChannel#flutter.baseflow.com/google_api_availability/methods( 8019): 	at com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(Unknown Source:3)
E/MethodChannel#flutter.baseflow.com/google_api_availability/methods( 8019): 	at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source:93)
E/MethodChannel#flutter.baseflow.com/google_api_availability/methods( 8019): 	at com.baseflow.googleapiavailability.GoogleApiAvailabilityPlugin.onMethodCall(GoogleApiAvailabilityPlugin.java:105)
E/MethodChannel#flutter.baseflow.com/google_api_availability/methods( 8019): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#flutter.baseflow.com/google_api_availability/methods( 8019): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#flutter.baseflow.com/google_api_availability/methods( 8019): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#flutter.baseflow.com/google_api_availability/methods( 8019): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.baseflow.com/google_api_availability/methods( 8019): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#flutter.baseflow.com/google_api_availability/methods( 8019): 	at android.os.Looper.loop(Looper.java:174)
```

**Comment by petermnt** [comment]
This is not an error related to this plugin.

I did notice an issue in your sample code though: keep in mind though that you should await the initialization of the plugin before registering your task.
