### ISSUE TITLE
App Crashes automatically 

### ISSUE THREAD

**Issue by sharad-paghadal** [vrtdev/flutter_workmanager#72]
```
2019-09-18 19:46:18.575 4430-4430/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.avinashi.meracrm_master_app, PID: 4430
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
        at com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin.registerWith(KeyboardVisibilityPlugin.java:107)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:19)
        at com.avinashi.meracrm_master_app.App.registerWith(Application.kt:15)
        at be.tramckrijte.workmanager.BackgroundWorker$doWork$1.run(BackgroundWorker.kt:71)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:6274)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
2019-09-18 19:46:18.952 4430-4496/com.avinashi.meracrm_master_app I/flutter: Observatory listening on http://127.0.0.1:47083/mRwMFBkhYAY=/
```

**Comment by sharad-paghadal** [comment]
I have found the cause of the crash. It's due to [keyboard_visibility](https://github.com/adee42/flutter_keyboard_visibility)
The issue has been already there on it's repo [#18](https://github.com/adee42/flutter_keyboard_visibility/issues/18)

**Comment by timrijckaert** [comment]
I see you answered your question. 😉

**Comment by sharad-paghadal** [comment]
The issue was because of dependency conflict. I have used `flutter_typeahead` which causes this crash. I have removed it and it's working fine.
