### ISSUE TITLE
Conflicts with flutter_plugin_pdf_viewer

### ISSUE THREAD

**Issue by winsonet** [vrtdev/flutter_workmanager#99]
when I try to work with [flutter_plugin_pdf_viewer](https://github.com/CrossPT/flutter_plugin_pdf_viewer) it shows below error:
```
W/System.err( 7995): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.app.Activity.getResources()' on a null object reference
W/System.err( 7995): 	at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin.getPage(FlutterPluginPdfViewerPlugin.java:128)
W/System.err( 7995): 	at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin.access$100(FlutterPluginPdfViewerPlugin.java:28)
W/System.err( 7995): 	at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin$1.run(FlutterPluginPdfViewerPlugin.java:68)
W/System.err( 7995): 	at android.os.Handler.handleCallback(Handler.java:873)
W/System.err( 7995): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 7995): 	at android.os.Looper.loop(Looper.java:193)
W/System.err( 7995): 	at android.os.HandlerThread.run(HandlerThread.java:65)
I/flutter ( 7995): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 7995): The following ArgumentError was thrown building MediaQuery(MediaQueryData(size: Size(432.0, 816.0),
I/flutter ( 7995): devicePixelRatio: 2.5, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding:
I/flutter ( 7995): EdgeInsets(0.0, 24.0, 0.0, 0.0), viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero,
I/flutter ( 7995): physicalDepth: 1.7976931348623157e+308, alwaysUse24HourFormat: false, accessibleNavigation: false,
I/flutter ( 7995): disableAnimations: false, invertColors: false, boldText: false)):
I/flutter ( 7995): Invalid argument(s) (path): Must not be null
```
I read the pdf viewer source code and find below
```
 Future<PDFPage> get({int page = 1}) async {
    assert(page > 0);
    var data = await _channel
        .invokeMethod('getPage', {'filePath': _filePath, 'pageNumber': page});
    return new PDFPage(data, page);
  }
```
it will return to null, I just start the backgound task with flutter_workmanager even nothing to do it will also cause the PDFViewer failed

I also read the plugin's [java code](https://github.com/CrossPT/flutter_plugin_pdf_viewer/blob/master/android/src/main/java/pt/tribeiro/flutter_plugin_pdf_viewer/FlutterPluginPdfViewerPlugin.java) and seems will also use the backgound handler, I am not sure whether the background process will be conflict with flutter_workmanager

but it works well on iOS

and I also read another issue[#64](https://github.com/vrtdev/flutter_workmanager/issues/64), I tried to add the `existingWorkPolicy` but nothing help, are there any other parameters or ways can solve this issue?

thanks a lot!

**Comment by timrijckaert** [comment]
Can you provide a sample with the least amount of code that demonstrates the issue.  

On another level why would want to generate a PDF in the background?  
Workmanager is used to offload tasks, but not as a replacement for foreground work that needs to be run in a different isolate. 
Again I don't know your usecase, but I would suggest looking into the [compute](https://api.flutter.dev/flutter/foundation/compute.html) function.

**Comment by timrijckaert** [comment]
#https://github.com/CrossPT/flutter_plugin_pdf_viewer/issues/41#issue-507604239

**Comment by winsonet** [comment]
I have created a demo project for this issue

[https://github.com/winsonet/flutter_pdf_viewer_issue_demo](https://github.com/winsonet/flutter_pdf_viewer_issue_demo)

**Comment by timrijckaert** [comment]
Hi @winsonet ,

It seems like the `flutter_pdf_viewer` assumes it will only be registered once.  
You can exclude a plugin from being registered again in the background isolate by implementing a custom `PluginRegistry`.

In your specific case your `App` file would like this.  

```
package com.pdf_view_sample

import be.tramckrijte.workmanager.WorkmanagerPlugin
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugins.GeneratedPluginRegistrant

class App : FlutterApplication(), PluginRegistry.PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        WorkmanagerPlugin.setPluginRegistrantCallback(this)
    }

    override fun registerWith(reg: PluginRegistry) {
        GeneratedPluginRegistrant.registerWith(RemoveSomePlugin(reg))
    }
}

class RemoveSomePlugin(private val reg: PluginRegistry) : PluginRegistry by reg {
    override fun hasPlugin(regKey: String): Boolean =
            if (regKey == "pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin") {
                true
            } else {
                reg.hasPlugin(regKey)
            }
}
```

Can you give it a go and check if that helps.

Thanks

**Comment by winsonet** [comment]
Thanks for your reply, but still not working :(
But it's ok, if can't solve it, I will change to use another pdf viewer plugin :)
Thanks!

**Comment by timrijckaert** [comment]
What do you mean it does not work?
I tried it and it works

**Comment by winsonet** [comment]
oh, I just tried to replace your codes in my App.kt file and run it in my demo app, and still show the errors as below:

```
D/EGL_emulation( 7135): eglMakeCurrent: 0xde126bc0: ver 3 0 (tinfo 0xe18ee3a0)
W/System  ( 7135): A resource failed to call close. 
I/flutter ( 7135): The background fetch was triggered  Test time: 1571578760761
I/WM-WorkerWrapper( 7135): Worker result SUCCESS for Work [ id=43f4449d-8445-4d58-8360-7cc840ec82ed, tags={ be.tramckrijte.workmanager.BackgroundWorker } ]
I/System.out( 7135): Attempt to invoke virtual method 'android.content.res.Resources android.app.Activity.getResources()' on a null object reference
W/System.err( 7135): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.app.Activity.getResources()' on a null object reference
W/System.err( 7135): 	at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin.getPage(FlutterPluginPdfViewerPlugin.java:128)
W/System.err( 7135): 	at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin.access$100(FlutterPluginPdfViewerPlugin.java:28)
W/System.err( 7135): 	at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin$1.run(FlutterPluginPdfViewerPlugin.java:68)
W/System.err( 7135): 	at android.os.Handler.handleCallback(Handler.java:873)
W/System.err( 7135): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 7135): 	at android.os.Looper.loop(Looper.java:193)
W/System.err( 7135): 	at android.os.HandlerThread.run(HandlerThread.java:65)

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following ArgumentError was thrown building MediaQuery(MediaQueryData(size: Size(432.0, 816.0), devicePixelRatio: 2.5, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding: EdgeInsets.zero, viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, physicalDepth: 1.7976931348623157e+308, alwaysUse24HourFormat: false, accessibleNavigation: false, disableAnimations: false, invertColors: false, boldText: false)):
Invalid argument(s) (path): Must not be null
```

**Comment by timrijckaert** [comment]
Hmm at this point, as you can see from the stack trace, it seems like a bug in the flutter pdf viewer library

**Comment by winsonet** [comment]
I see, but I just wonder you said you can let it works after changed?

**Comment by timrijckaert** [comment]
It seems to break at a later point.
Didn't test it thoroughly.

**Comment by winsonet** [comment]
I see, anyway, thanks a lot!
